name: Spring Boot CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    services:
      postgres-build:
        image: postgres
        env:
          POSTGRES_PASSWORD: 12345678
          POSTGRES_USER: postgres
          POSTGRES_DB: eventmanagement
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/eventmanagement
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 12345678
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: your-username/your-app:latest
    
    - name: Stop PostgreSQL service
      run: |
        # Find and stop the PostgreSQL container used during build
        docker ps -a
        POSTGRES_CONTAINER=$(docker ps -q --filter "ancestor=postgres")
        if [ ! -z "$POSTGRES_CONTAINER" ]; then
          docker stop $POSTGRES_CONTAINER
          docker rm $POSTGRES_CONTAINER
        fi
        # Wait to ensure the port is released
        sleep 10
    
    - name: Test with Docker Compose
      run: |
        
        docker compose up -d
        
        sleep 30
        
        docker compose down
